### ISSUE TITLE
Unexpected token export MsalProvider

### ISSUE THREAD

**Issue by ranshine** [Mimetis/msal-react-tester#21]
I am trying to use your create-react-app code for jest test cases, but i am getting unexpected token error

` FAIL  src/pages/SearchPage.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/sgorle/Desktop/msal-react-tester-main/create-react-app-sample/node_modules/@azure/msal-react/dist/index.js:3
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { MsalProvider } from '@azure/msal-react';
        | ^
      2 | import { render, screen } from '@testing-library/react';
      3 | import { MemoryRouter } from 'react-router-dom';
      4 | import Layout from '../components/Layout';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/pages/SearchPage.test.tsx:1:1)

 FAIL  src/pages/HomePage.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/sgorle/Desktop/msal-react-tester-main/create-react-app-sample/node_modules/@azure/msal-react/dist/index.js:3
    export { MsalConsumer, MsalContext } from './MsalContext.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import { act, render, screen } from '@testing-library/react';
    > 2 | import { MsalProvider } from '@azure/msal-react';
        | ^
      3 | import userEvent from '@testing-library/user-event';
      4 | import { MemoryRouter } from 'react-router-dom';
      5 | import Layout from '../components/Layout';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/pages/HomePage.test.tsx:2:1)`

**Comment by Mimetis** [comment]
The last version of **MSAL** is not working anymore with `create-react-app`.
If you can avoir using `create-react-app`, it's better, as it's not maintained anymore.

Also, take a look at https://github.com/Mimetis/msal-react-tester/issues/19 for more context

**Comment by darthsaderr** [comment]
I was able to get this working by doing the following:

Added `NODE_OPTIONS=--experimental-vm-modules` to the test script in package.json ([source](https://jestjs.io/docs/ecmascript-modules))
Renamed the relevant test files from .test.js to .test.jsx and added `extensionsToTreatAsEsm: ['.jsx']` to jest.config ([source](https://jestjs.io/docs/ecmascript-modules))
in jest.config, set `transformIgnorePatterns: ["/node_modules/(?!(@azure)/)"]` ([source](https://github.com/jestjs/jest/issues/14805#issuecomment-1895236885))
also, not sure how this changed things but if I take it out, it breaks again, in jest.config: ([source](https://jestjs.io/docs/configuration#testmatch-arraystring))
`testMatch: [
    "**/__tests__/**/*.?(m)[jt]s?(x)",
    "**/?(*.)+(spec|test).?(m)[jt]s?(x)",
  ],`

I can't promise this is the most efficient or correct workaround, but it's something

**Comment by Mimetis** [comment]
nice !! Can you make a small PR in the sample folder to make it working ?

**Comment by darthsaderr** [comment]
Well it's not entirely working. All that got the import/export errors to go away but now I'm getting this and I can't find anything that fixes it

```
TypeError: Cannot read properties of undefined (reading 'mockImplementation')

      12 |   beforeEach(() => {
      13 |     msalTester = new MsalReactTester();
    > 14 |     msalTester.spyMsal();
         |                ^
      15 |   });
      16 |
      17 |   afterEach(() => {

      at MsalReactTester.spyMsal (node_modules/msal-react-tester/src/MsalReactTester.ts:167:58)
      at Object.spyMsal (__tests__/client/components/TopNav.test.jsx:14:16)
```

**Comment by francoexequielschuler** [comment]
Hey, any updates on this? Still getting the token error using vite + jest

```
export { default as MsalReactTester } from './MsalReactTester.js';
^^^^^^

    SyntaxError: Unexpected token 'export'
```

**Comment by Mimetis** [comment]
If you are using vite, it should work
