### ISSUE TITLE
An update to MsalProvider inside a test was not wrapped in act(...).

### ISSUE THREAD

**Issue by llmdev** [Mimetis/msal-react-tester#7]
I'm having multiple errors of this type, how to solve?

```js
 console.error
    Warning: An update to MsalProvider inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at MsalProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@azure/msal-react/src/MsalProvider.tsx:101:31)
        at DialogProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-context/dist/packages/react/context/src/createContext.tsx:58:15)
        at Dialog (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-dialog/dist/packages/react/dialog/src/Dialog.tsx:53:5)
        at Drawer
        at wrapper (/Users/colaborador/projects/clickgb-local-environment/frontend/src/modules/sideBar/profileMenu.test.tsx:38:19)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at updateState (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at node_modules/@azure/msal-react/src/MsalProvider.tsx:120:13
      at node_modules/msal-react-tester/src/MsalReactTester.ts:169:10
          at Array.forEach (<anonymous>)
```

**Comment by Mimetis** [comment]
Hello @llmdev 

I'm not sure about your issue, maybe sharing a little bit of your code would help to figure it out.

Just in case, often this error is coming when you are doing an assertion before getting the result from an http call.

Can you look at this issue answer I provided here https://github.com/Mimetis/msal-react-tester/issues/3#issuecomment-1305459977 and see if it's your case ?

**Comment by llmdev** [comment]
```js
describe('<ProfileMenu />', () => {
  const accountInfo: AccountInfo = {
    homeAccountId: 'home-account-id',
    localAccountId: 'local-account-id',
    environment: 'login.windows.net',
    tenantId: 'tenant-id',
    username: 'john.doe@contoso.com',
    name: 'John Doe',
    idTokenClaims: {
      given_name: 'Giorgio',
    },
  };

  const msalTester = new MsalReactTester('Redirect', accountInfo);
  msalTester.spyMsal();
  msalTester.isLogged();

  it.only('should display the profile menu', () => {
    const history = createMemoryHistory();
    render(<ProfileMenu />, {
      wrapper: ({ children }) => (
        <Drawer>
          <MsalProvider instance={msalTester.client}>
            <Router history={history}>
              <GolobalStore stores={[useUserStore]}>{children}</GolobalStore>
            </Router>
          </MsalProvider>
        </Drawer>
      ),
    });

    expect(screen.getByRole('link')).toBeInTheDocument();
  });
```

```js

export const useUserStore = () => {
  const [user, setUser] = useState<UserData>();
  const { accounts } = useMsal();

  const adUser = {
    ...accounts[0],
    profile: {
      ...accounts[0].idTokenClaims
    },
  };

  useEffect(() => {
    setUser(adUser);
  }, []);

  return { adUser };
};

```

```js

export const GolobalStore = ({ stores, children }) => {
  // complain if no instances provided for initialization
  if (!stores || !stores.length) {
    throw new Error(
      'You must provide stores list to a <GlobalStore> for initialization!'
    );
  }

  // create providers for each store
  let providersLayout;

  stores.forEach((store) => {
    let context = ContextMap.get(store);
    if (!context) {
      context = React.createContext(null);
      ContextMap.set(store, context);
    }
    providersLayout = (
      <Provider store={store}>{providersLayout || children}</Provider>
    );
  });
  return providersLayout;
};

export function useStore<T>(storeInit): T {
  // use store specific context
  const map = React.useContext<any>(ContextMap.get(storeInit));

  // complain if no map is given
  if (!map) {
    throw new Error('You must wrap your components with a <Provider>!');
  }

  const instance = map.get(storeInit);

  // complain if instance wasn't initialized
  if (!instance) {
    throw new Error('Provided store instance did not initialize correctly!');
  }

  return instance;
}
```

**Comment by llmdev** [comment]
```js
function ProfileMenu() {
  const { user } = useStore<UserStoreState>(useUserStore);

  return (
    <Box
      css={style.profile}
    >
      <Text
        css={style.userName}
        color="$medium-light-1"
      >
        {user?.profile.given_name}
      </Text>

      <DrawerTrigger>
        <Link
          role="link"
          to="/perfil"
          style={style.link}
        >
          <Text
            color="$actionNavigationStandardStatic"
            size="auxiliarSmall"
          >
            Ver meu perfil
          </Text>
        </Link>
      </DrawerTrigger>
    </Box>
  );
}
```

**Comment by llmdev** [comment]
I'm new to writing tests

**Comment by llmdev** [comment]
Sorry, I'm reviewing my implementation, I already put it here

**Comment by llmdev** [comment]
My Test

```js
describe('<ProfileMenu />', () => {
  const accountInfo: AccountInfo = {
    homeAccountId: 'home-account-id',
    localAccountId: 'local-account-id',
    environment: 'login.windows.net',
    tenantId: 'tenant-id',
    username: 'john.doe@contoso.com',
    name: 'John Doe',
    idTokenClaims: {
      given_name: 'Giorgio',
    },
  };

  const msalTester = new MsalReactTester('Redirect', accountInfo);
  msalTester.spyMsal();
  msalTester.isLogged();

  it.only('should display the profile menu', () => {
    const history = createMemoryHistory();
    render(<ProfileMenu />, {
      wrapper: ({ children }) => (
        <Drawer>
          <MsalProvider instance={msalTester.client}>
            <Router history={history}>
              <div>{children}</div>
            </Router>
          </MsalProvider>
        </Drawer>
      ),
    });

    expect(screen.getByRole('link')).toBeInTheDocument();
  });
});

```


Compoment
```js
function ProfileMenu() {
  const { user } = useUserStore();

  return (
    <Box
      css={style.profile}
    >
      <Text
        css={style.userName}
        color="$medium-light-1"
      >
        {user?.idTokenClaims?.given_name}
      </Text>

      <DrawerTrigger>
        <Link
          role="link"
          to="/perfil"
          style={style.link}
        >
          <Text
            color="$actionNavigationStandardStatic"
            size="auxiliarSmall"
          >
            Ver meu perfil
          </Text>
        </Link>
      </DrawerTrigger>
    </Box>
  );
}

```

```js
import { useEffect, useState } from 'react';
import { UserData } from '@app/contracts/IUser';
import { useMsal } from '@azure/msal-react';

export const useUserStore = () => {
  const [user, setUser] = useState<UserData>({});
  const { accounts } = useMsal();

  useEffect(() => {
    setUser({ ...accounts[0] });
  }, [accounts]);

  return { user };
};

```

Now it's correct, still terminal returns me


```bash
console.error
    Warning: An update to MsalProvider inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at MsalProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@azure/msal-react/src/MsalProvider.tsx:101:31)
        at DialogProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-context/dist/packages/react/context/src/createContext.tsx:58:15)
        at Dialog (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-dialog/dist/packages/react/dialog/src/Dialog.tsx:53:5)
        at Drawer
        at wrapper (/Users/colaborador/projects/clickgb-local-environment/frontend/src/modules/sideBar/profileMenu.test.tsx:36:19)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at updateState (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at node_modules/@azure/msal-react/src/MsalProvider.tsx:120:13
      at node_modules/msal-react-tester/src/MsalReactTester.ts:169:10
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/msal-react-tester/src/MsalReactTester.ts:168:28)
      at node_modules/@azure/msal-react/src/MsalProvider.tsx:132:22

  console.error
    Warning: An update to MsalProvider inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at MsalProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@azure/msal-react/src/MsalProvider.tsx:101:31)
        at DialogProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-context/dist/packages/react/context/src/createContext.tsx:58:15)
        at Dialog (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-dialog/dist/packages/react/dialog/src/Dialog.tsx:53:5)
        at Drawer
        at wrapper (/Users/colaborador/projects/clickgb-local-environment/frontend/src/modules/sideBar/profileMenu.test.tsx:36:19)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at updateState (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at node_modules/@azure/msal-react/src/MsalProvider.tsx:120:13
      at MsalReactTester.<anonymous> (node_modules/msal-react-tester/src/MsalReactTester.ts:182:9)
      at step (node_modules/msal-react-tester/dist/index.js:66:23)
      at Object.next (node_modules/msal-react-tester/dist/index.js:47:53)
      at node_modules/msal-react-tester/dist/index.js:40:71
      at __awaiter (node_modules/msal-react-tester/dist/index.js:36:12)
      at node_modules/msal-react-tester/src/MsalReactTester.ts:181:51
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/msal-react-tester/src/MsalReactTester.ts:181:28)
      at node_modules/@azure/msal-react/src/MsalProvider.tsx:132:22

  console.error
    Warning: An update to MsalProvider inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at MsalProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@azure/msal-react/src/MsalProvider.tsx:101:31)
        at DialogProvider (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-context/dist/packages/react/context/src/createContext.tsx:58:15)
        at Dialog (/Users/colaborador/projects/clickgb-local-environment/frontend/node_modules/@radix-ui/react-dialog/dist/packages/react/dialog/src/Dialog.tsx:53:5)
        at Drawer
        at wrapper (/Users/colaborador/projects/clickgb-local-environment/frontend/src/modules/sideBar/profileMenu.test.tsx:36:19)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at updateState (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at node_modules/@azure/msal-react/src/MsalProvider.tsx:140:17

 PASS  src/modules/sideBar/profileMenu.test.tsx
  <ProfileMenu />
    ✓ should display the profile menu (203 ms)
```

**Comment by Mimetis** [comment]
I've made this test and it's working fine for me:

``` tsx

describe('ProfileMenu', () => {

  const accountInfo: AccountInfo = {
    homeAccountId: 'home-account-id',
    localAccountId: 'local-account-id',
    environment: 'login.windows.net',
    tenantId: 'tenant-id',
    username: 'john.doe@contoso.com',
    name: 'John Doe',
    idTokenClaims: {
      given_name: 'Giorgio',
    },
  };

  let msalTester: MsalReactTester;
  beforeEach(() => {
    // new instance of msal tester for each test
    msalTester = new MsalReactTester('Redirect', accountInfo);

    // spy all required msal things
    msalTester.spyMsal();
  });

  afterEach(() => {
    msalTester.resetSpyMsal();
  });

  test('ProfileMenu is logged', async () => {

    msalTester.isLogged();
    render(
      <MsalProvider instance={msalTester.client}>
        <MemoryRouter>
          <Layout>
            <ProfileMenu />
          </Layout>
        </MemoryRouter>
      </MsalProvider>,
    );

    await msalTester.waitForRedirect();
    expect(screen.getByText(/Giorgio/)).toBeInTheDocument();
  });

});
```

I guess your problem is coming from your `wrapper` / `render` (maybe)

**Comment by llmdev** [comment]
I added this snippet to my code and it solved

```js
 await msalTester.waitForRedirect();
```

 wanted to better understand what this is doing.

```js
  it.only('should display the profile menu',  async () => {
    const history = createMemoryHistory();
    render(<ProfileMenu />, {
      wrapper: ({ children }) => (
        <Drawer>
          <MsalProvider instance={msalTester.client}>
            <Router history={history}>
              <div>{children}</div>
            </Router>
          </MsalProvider>
        </Drawer>
      ),
    });

    await msalTester.waitForRedirect();
    expect(screen.getByRole('link')).toBeInTheDocument();
  });
```

I am very grateful for helping me, I saw in the documentation that it expects to run Msal processes.. I need to study more to understand these rendering flows, maybe that's it.

sorry for my terrible English

and thanks for helping the community =D

**Comment by Mimetis** [comment]
ah ah sorry, I should have seen it before :)
